# Generated by Django 3.2 on 2025-10-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='semester',
            field=models.IntegerField(default=114),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(choices=[('NYCU_NTHU', '清交聯賽'), ('freshman cup', '新生盃'), ('NYCU cup', '交大盃')], max_length=20),
        ),
    ]
