# Generated by Django 3.2 on 2025-10-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20251001_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='innings',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
