# Generated by Django 3.2 on 2025-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_match_match_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='table',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_number',
            field=models.IntegerField(unique=True),
        ),
    ]
