# Generated by Django 3.2 on 2025-10-02 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_annoucement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annoucement',
            new_name='Announcement',
        ),
    ]
