# Generated by Django 3.2 on 2025-10-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_rename_annoucement_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='point1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='point2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
