# Generated by Django 3.2 on 2025-10-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20251002_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='point1',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='match',
            name='point2',
            field=models.CharField(default='', max_length=3),
        ),
    ]
