# Generated by Django 3.2 on 2025-10-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20251002_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='semester',
            field=models.CharField(max_length=20),
        ),
    ]
