# Generated by Django 3.2 on 2025-10-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_number',
            field=models.IntegerField(),
        ),
    ]
