# Generated by Django 3.2 on 2025-10-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_alter_match_match_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='player_num',
            field=models.IntegerField(default=64),
            preserve_default=False,
        ),
    ]
