# Generated by Django 3.2 on 2025-10-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_tournament_player_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='advance_per_group',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='group_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='num_groups',
            field=models.IntegerField(null=True),
        ),
    ]
