# Generated by Django 3.2 on 2025-10-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20251009_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='advance_per_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='group_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='num_groups',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
