# Generated by Django 3.2 on 2025-11-14 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_match_loser'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
