# Generated by Django 3.2 on 2025-11-14 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_announcement_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 11, 21)),
        ),
    ]
